DROP DATABASE IF EXISTS bookdb;
DROP USER IF EXISTS `bookadmin`@`%`;
DROP USER IF EXISTS `bookuser`@`%`;

CREATE DATABASE IF NOT EXISTS bookdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE bookdb;

CREATE USER IF NOT EXISTS `bookadmin`@`%` IDENTIFIED WITH caching_sha2_password BY 'passWord%1';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, REFERENCES, INDEX,
    EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER
ON bookdb.* TO `bookadmin`@`%`;

CREATE USER IF NOT EXISTS `bookuser`@'%' IDENTIFIED WITH caching_sha2_password BY 'passWord%2';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON bookdb.* TO `bookuser`@`%`;

FLUSH PRIVILEGES;
